MVC CRUD using asp.net core (.net 6)/Models/AddActorViewModel.cs
namespace MVC_CRUD_using_asp.net_core__.net_6_.Models
{
    public class AddActorViewModel
    {
        public string Name { get; set; }
        public string CarrierBest { get; set; }

        public int Salary { get; set; }
    }
}

MVC CRUD using asp.net core (.net 6)/Models/Domain/ActorModel.cs
namespace MVC_CRUD_using_asp.net_core__.net_6_.Models.Domain
{
    public class ActorModel

    {

        public Guid Id { get; set; } 
        public string Name { get; set; }    
        public string CarrierBest { get; set; }

        public int Salary { get; set; }

    }
}

MVC CRUD using asp.net core (.net 6)/Models/ErrorViewModel.cs
namespace MVC_CRUD_using_asp.net_core__.net_6_.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC CRUD using asp.net core (.net 6)/Models/UpdateActorViewModel.cs
namespace MVC_CRUD_using_asp.net_core__.net_6_.Models
{
    public class UpdateActorViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string CarrierBest { get; set; }

        public int Salary { get; set; }
    }
}

MVC CRUD using asp.net core (.net 6)/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_CRUD_using_asp.net_core__.net_6_.Models;
using MVC_CRUD_using_asp.net_core__.net_6_.Models.Domain;
using MVC_CRUD_using_asp.net_core__.net_6_.Repositary;

namespace MVC_CRUD_using_asp.net_core__.net_6_.Controllers
{
    public class ActorsController : Controller
    {
        private readonly MVCDemoDbContext mvcDemoDbContext;

        public ActorsController(MVCDemoDbContext mvcDemoDbContext)
        {
            this.mvcDemoDbContext = mvcDemoDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var actors = await mvcDemoDbContext.Actors.ToListAsync();
            return View(actors);
        }



        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Add(AddActorViewModel addActorRequest)
        {
            var actor = new ActorModel()
            {
                Id = Guid.NewGuid(),
                Name = addActorRequest.Name,
                CarrierBest = addActorRequest.CarrierBest,
                Salary = addActorRequest.Salary
            };
            await mvcDemoDbContext.Actors.AddAsync(actor);
            await mvcDemoDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var act = await mvcDemoDbContext.Actors.FirstOrDefaultAsync(x=>x.Id== id);
            if(act != null)
            {
                var viewModel = new UpdateActorViewModel()
                {
                    Id = act.Id,
                    Name = act.Name,
                    CarrierBest = act.CarrierBest,
                    Salary = act.Salary

                };
                return await Task.Run(()=> View("View",viewModel));
            }
           
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> View(UpdateActorViewModel model)
        {
            var act = await mvcDemoDbContext.Actors.FindAsync(model.Id);
            if(act != null )
            {
                act.Name = model.Name;  
                act.CarrierBest = model.CarrierBest;
                act.Salary = model.Salary;

                await mvcDemoDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateActorViewModel model)
        {
            var act = await mvcDemoDbContext.Actors.FindAsync(model.Id);
            if(act != null)
            {
                mvcDemoDbContext.Actors.Remove(act);
                await mvcDemoDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }


    }
}

MVC CRUD using asp.net core (.net 6)/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_CRUD_using_asp.net_core__.net_6_.Models;
using System.Diagnostics;

namespace MVC_CRUD_using_asp.net_core__.net_6_.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC CRUD using asp.net core (.net 6)/Views/Actors/Add.cshtml
@model MVC_CRUD_using_asp.net_core__.net_6_.Models.AddActorViewModel 
@{
}
<h1>Enter Actors Details</h1>
<form method="post" action="Add"class="mt-5" style="background-color:aquamarine;">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Actor's Carrier Best</label>
        <input type="text" class="form-control" asp-for="CarrierBest">
    </div>
    
    <div class="mb-3">
        <label for="" class="form-label">Remuneration</label>
        <input type="number" class="form-control" asp-for="Salary">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MVC CRUD using asp.net core (.net 6)/Views/Actors/Index.cshtml
@model List<MVC_CRUD_using_asp.net_core__.net_6_.Models.Domain.ActorModel>

@{
}

<h1>Actors</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Carrier Best Movie</th>
            <th>Salary(in Crores)</th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var act in Model)
        {
            <tr>
                <td>@act.Id</td>
                <td>@act.Name</td>
                <td>@act.CarrierBest</td>
                <td>@act.Salary</td>
                <td> <a href="Actors/View/@act.Id">View</a></td>
            </tr>
        }

    </tbody>

</table>

MVC CRUD using asp.net core (.net 6)/Views/Actors/View.cshtml
@model MVC_CRUD_using_asp.net_core__.net_6_.Models.UpdateActorViewModel
@{
}

<h1>Edit Details</h1>
<form method="post" action="View" class="mt-5" style="background-color:rosybrown">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Actor's Carrier Best</label>
        <input type="text" class="form-control" asp-for="CarrierBest">
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Remuneration</label>
        <input type="number" class="form-control" asp-for="Salary">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

    <button type="submit" class="btn btn-danger" asp-controller="Actors" asp-action="Delete" >Delete</button>
</form>

MVC CRUD using asp.net core (.net 6)/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" >

    <h1 class="display-4" style="font-family:'Times New Roman'; margin:initial;" >Designed by Varma</h1>
    
</div>

MVC CRUD using asp.net core (.net 6)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_CRUD_using_asp.net_core__.net_6_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css"/>
    <link rel="stylesheet" href="~/MVC_CRUD_using_asp.net_core__.net_6_.styles.css" asp-append-version="true" />
</head>
<body >
    <header>
        
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" >
            <div class="container-fluid">
        
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                 
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="varma">

                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Add">Add Actor</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Index">Show Actors</a>
                            </li>
                        </ul>
                    </div>

                
            </div>
        </nav>
        
    </header>




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
  
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>